version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8080

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - ml-service
    environment:
      - ML_SERVICE_URL=http://ml-service:8000
      - ConnectionStrings__DefaultConnection=Data Source=./data/dataset.db

  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ml-service/data:/app/data
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  data:
